//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TacticView.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TacticView.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRs marked servicing-approved.
        /// </summary>
        internal static string ApprovedDescription {
            get {
                return ResourceManager.GetString("ApprovedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cached data.
        /// </summary>
        internal static string CacheText {
            get {
                return ResourceManager.GetString("CacheText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PRs marked servicing-consider.
        /// </summary>
        internal static string ConsiderDescription {
            get {
                return ResourceManager.GetString("ConsiderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone.
        /// </summary>
        internal static string MilestoneHeader {
            get {
                return ResourceManager.GetString("MilestoneHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an Issue.
        /// </summary>
        internal static string ReportAnIssue {
            get {
                return ResourceManager.GetString("ReportAnIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching the interwebs.
        /// </summary>
        internal static string SearchingPlaceholder {
            get {
                return ResourceManager.GetString("SearchingPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicing Approved.
        /// </summary>
        internal static string ServicingApprovedLong {
            get {
                return ResourceManager.GetString("ServicingApprovedLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string ServicingApprovedShort {
            get {
                return ResourceManager.GetString("ServicingApprovedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicing Consider.
        /// </summary>
        internal static string ServicingConsiderLong {
            get {
                return ResourceManager.GetString("ServicingConsiderLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider.
        /// </summary>
        internal static string ServicingConsiderShort {
            get {
                return ResourceManager.GetString("ServicingConsiderShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string TitleHeader {
            get {
                return ResourceManager.GetString("TitleHeader", resourceCulture);
            }
        }
    }
}
